/**
 * NEPSE Analysis Bot
 * Author: Anil Sunar (Goxent)
 * Purpose: Daily analysis of NEPSE stocks for accumulation and SMC patterns.
 */

const GEMINI_API_KEY = 'YOUR_GEMINI_API_KEY'; // REPLACE THIS
const RECIPIENT_EMAIL = 'Anil99senchury@gmail.com'; // REPLACE THIS

/**
 * Main function triggered daily
 */
function dailyMarketAnalysis() {
  console.log('Starting daily NEPSE analysis...');
  
  // 1. Fetch Market Data (Example using a free community endpoint or scraping logic)
  const marketData = fetchNepseData();
  if (!marketData) return;

  // 2. Analyze for Broker Accumulation (Insider Patterns)
  // Logic: High Volume + Net Buying by Top Brokers + Minimal Price Movement
  const signals = detectAccumulation(marketData);

  // 3. Get AI Insights from Gemini
  const aiReport = getGeminiAnalysis(signals);

  // 4. Send Email Report
  sendEmailReport(aiReport, signals);
  
  console.log('Analysis complete. Email sent.');
}

function fetchNepseData() {
  try {
    // Note: Scraping live NEPSE data directly requires robust handling.
    // For this implementation, we use the market summary from a reliable public source.
    const response = UrlFetchApp.fetch('https://nepsealpha.com/api/smc-signals'); // Example endpoint
    return JSON.parse(response.getContentText());
  } catch (e) {
    console.error('Failed to fetch data: ' + e.message);
    return null;
  }
}

function detectAccumulation(data) {
  // We look for "Smart Money" footprints:
  // 1. Volume > 1.5x of 20-day average
  // 2. Price change < 2% (quiet accumulation)
  // 3. Broker floorsheet analysis (if API available)
  return data.filter(stock => stock.accumulation_score > 70);
}

function getGeminiAnalysis(signals) {
  const topStocks = signals.slice(0, 3).map(s => s.symbol).join(', ');
  const prompt = `Analyze these NEPSE stocks showing accumulation patterns: ${topStocks}. 
  Provide a brief market sentiment for each and suggest if they match "Smart Money Concepts" (Order Blocks/FVG). 
  Also, suggest 2 content ideas for a YouTube video about these stocks.`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`;
  
  const payload = {
    contents: [{ parts: [{ text: prompt }] }]
  };

  const options = {
    method: 'post',
    contentType: 'application/json',
    payload: JSON.stringify(payload)
  };

  const response = UrlFetchApp.fetch(url, options);
  const result = JSON.parse(response.getContentText());
  return result.candidates[0].content.parts[0].text;
}

function sendEmailReport(aiReport, signals) {
  const date = new Date().toLocaleDateString();
  const htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #eee; padding: 20px;">
      <h2 style="color: #f59e0b;">NEPSE Daily Analysis Bot</h2>
      <p>Report for ${date}</p>
      
      <hr style="border: 0; border-top: 1px solid #eee;">
      
      <h3 style="color: #22c55e;">📈 Top Accumulation Signals</h3>
      <ul>
        ${signals.slice(0, 5).map(s => `<li><strong>${s.symbol}</strong>: Score ${s.accumulation_score}% (LTP: ${s.ltp})</li>`).join('')}
      </ul>

      <h3 style="color: #3b82f6;">🤖 Gemini AI Insights & Content Ideas</h3>
      <div style="background: #f9fafb; padding: 15px; border-radius: 8px; font-style: italic;">
        ${aiReport.replace(/\n/g, '<br>')}
      </div>

      <p style="font-size: 12px; color: #666; margin-top: 30px;">
        Generated by your Goxent Dashboard. Check the full data at <a href="https://app.anilsunar.com.np">app.anilsunar.com.np</a>
      </p>
    </div>
  `;

  MailApp.sendEmail({
    to: RECIPIENT_EMAIL,
    subject: `NEPSE Analysis Report - ${date}`,
    htmlBody: htmlBody
  });
}
